Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-12, with the labels that each got.

#1169 Fix volume of startup sound
  scripts/inc.writeGlobalConfig.sh
Labels: bug

#1168 Add version number to startup script
  scripts/startup-scripts.sh
Labels: enhancement

#1179 missing savepos-command in "playerstopafter"
  scripts/playout_controls.sh
Labels: bug

#1161 Update Mopidy Iris to 3.54.2
  requirements-spotify.txt
Labels: enhancement, spotify edition
