Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-11, with the labels that each got.

#1124 Removed unnecessary SHUFFLE code
  scripts/inc.settingsFolderSpecific.sh
Labels: bash, bug

#1143 Fix #1141
  components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
Labels: bug

#1149 Fix resume
  scripts/resume_play.sh
Labels: bug

#1147 Fix for #1133 (Update i2c_lcd.py to fix track number)
  components/displays/HD44780-i2c/i2c_lcd.py
Labels: bug, python

#1154 Make sure, SPI works
  components/rfid-reader/RC522/setup_rc522.sh
Labels: enhancement

#1138 Added option to display case specific system info
  htdocs/inc.addSystemInfo.php
  htdocs/systemInfo.php
Labels: enhancement, php

#1155 Update README.md
  README.md
Labels: enhancement

#1166 Improve reading artist
  components/displays/HD44780-i2c/i2c_lcd.py
Labels: enhancement

#1165 Feature/gpio debugging
  components/gpio_control/GPIODevices/simple_button.py
  components/gpio_control/GPIODevices/two_button_control.py
Labels: enhancement
