Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-05, with the labels that each got.

#909 add changes proposed in #889 to fix repeat function
  htdocs/inc.loadControls.php
Labels: bug

#918 Use pytest in github actions
  .github/workflows/pythonpackage.yml
  components/gpio_control/requirements.txt
Labels: enhancement

#943 Add setup scripts for PN532 RFID reader and PirateAudio HAT
  components/audio/PirateAudioHAT/README.md
  components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
  components/rfid-reader/PN532/README.md
  components/rfid-reader/PN532/reset_pn532.sh
  components/rfid-reader/PN532/setup_pn532.sh
  scripts/Reader.py
  scripts/installscripts/buster-install-default.sh
Labels: enhancement

#859 Added feature to use LCD displays based on HD44780 connected via i2c …
  components/displays/HD44780-i2c/README.md
  components/displays/HD44780-i2c/i2c-lcd.service.default.sample
  components/displays/HD44780-i2c/i2c_lcd.py
  components/displays/HD44780-i2c/i2c_lcd_driver.py
Labels: enhancement

#955 Move RC522 related setup to components folder
  components/rfid-reader/PN532/requirements.txt
  components/rfid-reader/RC522/README.md
  components/rfid-reader/RC522/requirements.txt
  requirements.txt
Labels: bug, enhancement

#957 Finally fix docker test
  ci/Dockerfile.buster.test_install.amd64
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#953 Function based mopidy api calls
  htdocs/func.php
  htdocs/inc.viewFolderTree.php
Labels: enhancement

#968 add a script to install RC522 reader
  components/rfid-reader/PN532/README.md
  components/rfid-reader/RC522/README.md
  components/rfid-reader/RC522/setup_rc522.sh
Labels: enhancement

#977 Update Reader.py.experimental
  scripts/Reader.py.experimental
Labels: bug

#983 Fix bug in csv import
  htdocs/cardRegisterNew.php
Labels: bug

#989 Fix permissions for mpd.log
  scripts/installscripts/buster-install-default.sh
Labels: enhancement

#987 Reduce bounce time of buttons
  misc/sampleconfigs/gpio-buttons.py.sample
Labels: enhancement
