Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-10, with the labels that each got.

#1062 Pull Up / Down Configuration for Simple Button / rotary Encoder for Prev_Next Control
  components/gpio_control/GPIODevices/simple_button.py
  components/gpio_control/example_configs/gpio_setting_rotary_vol_prevnext.ini
  components/gpio_control/example_configs/gpio_settings.ini
  components/gpio_control/gpio_control.py
Labels: enhancement

#1115 Fix Samba WINS configuration
  scripts/installscripts/buster-install-default.sh
Labels: enhancement

#1123 Update the install script for hotspot to the 2.1 changes
  scripts/installscripts/buster-install-default-with-autohotspot.sh
Labels: bash, enhancement

#1121 Commenting out unnecessary shuffle for testing purposes
  htdocs/inc.loadedPlaylist.php
  scripts/inc.settingsFolderSpecific.sh
Labels: bash, enhancement

#1118 Added customizable poweroff command
  scripts/inc.writeGlobalConfig.sh
  scripts/playout_controls.sh
Labels: bash, enhancement

#1116 Fix gpio_settings.ini paths
  components/gpio_control/README.md
  components/gpio_control/install.sh
  misc/sampleconfigs/gpio_settings.ini.sample
  scripts/installscripts/buster-install-default.sh
Labels: bug
