Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-03, with the labels that each got.

#822 Use requirements.txt
  requirements-spotify.txt
  scripts/installscripts/buster-install-mopidy3.sh
Labels: enhancement

#841 chore: let issues be unassigned by default
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
Labels: enhancement

#835 Merge the mopidy3 install script into buster-install-default.sh
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/buster-install-mopidy3.sh
Labels: enhancement

#839 chore: remove php-fpm
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/stretch-install-default.sh
  scripts/installscripts/stretch-install-spotify.sh
Labels: enhancement, need more info

#847 fix: cd into phoniebox code dir before installing spotify deps
  scripts/installscripts/buster-install-default.sh
Labels: bug, spotify edition

#843 Hotfix: installation of py packages now for python 3
  scripts/installscripts/buster-install-default.sh
Labels: bug

#857 use non-interactive debian frontend in dockerfiles
  ci/Dockerfile.buster.amd64
  ci/Dockerfile.buster.armv7
  ci/Dockerfile.stretch.amd64
  ci/Dockerfile.stretch.armv7
Labels: enhancement

#840 chore: cleanup local copy of ondryaso/pi-rc522
  scripts/pirc522/__init__.py
  scripts/pirc522/rfid.py
  scripts/pirc522/util.py
Labels: enhancement

#846 (WIP) Github action to run Docker image and (integration) tests with pytest
  .github/workflows/dockerimage.yml
  ci/Dockerfile.buster.amd64
Labels: enhancement

#825 Add support for PN532 based RFID readers
  components/rfid-reader/PN532/README.md
  components/rfid-reader/PN532/requirements.txt
  scripts/Reader.py
  scripts/Reader.py.experimental
  scripts/Reader.py.original
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/stretch-install-default.sh
  scripts/installscripts/stretch-install-spotify.sh
Labels: enhancement

#831 [WIP] Improve version info
  scripts/installscripts/buster-install-default.sh
  settings/version
Labels: enhancement

#879 Add info about pkg installation
  components/smart-home-automation/MQTT-protocol/README.md
Labels: enhancement
