Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2020-04, with the labels that each got.

#891 Fix adding git hash to version
  scripts/installscripts/buster-install-default.sh
  settings/version
Labels: bug

#888 Use functions, format if-conditions in install script
  scripts/installscripts/buster-install-default.sh
Labels: enhancement

#895 Add dependency for Gmusic
  requirements-gmusic.txt
Labels: bug, spotify edition

#785 Append file to playlist
  htdocs/api/playlist/appendFileToPlaylist.php
  htdocs/func.php
  htdocs/js/jukebox.js
  htdocs/search.php
  scripts/playout_controls.sh
Labels: enhancement

#763 RotaryEncoder based on gpiozero
  components/__init__.py
  components/gpio_control/GPIODevices/__init__.py
  components/gpio_control/GPIODevices/rotary_encoder.py
  components/gpio_control/GPIODevices/shutdown_button.py
  components/gpio_control/GPIODevices/simple_button.py
  components/gpio_control/GPIODevices/two_button_control.py
  components/gpio_control/README.md
  components/gpio_control/__init__.py
  components/gpio_control/example_configs/gpio_settings.ini
  components/gpio_control/example_configs/gpio_settings_test.ini
  components/gpio_control/example_configs/phoniebox_gpio_control.service
  components/gpio_control/function_calls.py
  components/gpio_control/gpio_control.py
  components/gpio_control/install.sh
  components/gpio_control/test/__init__.py
  components/gpio_control/test/conftest.py
  components/gpio_control/test/gpio_settings_test.ini
  components/gpio_control/test/test_RotaryEncoder.py
  components/gpio_control/test/test_SimpleButton.py
  components/gpio_control/test/test_TwoButtonControl.py
  components/gpio_control/test/test_gpio_control.py
  components/gpio_control/test/test_shutdown_button.py
  requirements.txt
  scripts/__init__.py
  scripts/rotary-encoder.py
  scripts/rotary_encoder_base.py
  scripts/test/mockedGPIO.py
  scripts/test/test_TwoButtonControl.py
  settings/gpio_settings.ini
Labels: enhancement

#903 Add test_installation.sh script
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#907 Install script improvements2
  scripts/installscripts/buster-install-default.sh
Labels: enhancement

#902 DE translations adapted to latest EN changes
  htdocs/lang/lang-de-DE.php
  htdocs/lang/lang-en-UK.php
Labels: enhancement

#906 Feature/configureable gpio buttons
  components/gpio_control/GPIODevices/VolumeControl.py
  components/gpio_control/GPIODevices/__init__.py
  components/gpio_control/GPIODevices/led.py
  components/gpio_control/check_installation.sh
  components/gpio_control/example_configs/gpio_settings_rotary_and_led.ini
  components/gpio_control/function_calls.py
  components/gpio_control/gpio_control.py
  components/gpio_control/install.sh
  components/gpio_control/requirements.txt
Labels: bug
