Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2021-01, with the labels that each got.

#1209 Added stop on removal functionality example
  components/gpio_control/example_configs/gpio_settings.ini
Labels: enhancement

#1249 feat: GPIO Buttons over USB Encoder
  components/controls/__init__.py
  components/controls/buttons_usb_encoder/README.md
  components/controls/buttons_usb_encoder/__init__.py
  components/controls/buttons_usb_encoder/buttons-usb-encoder.jpg
  components/controls/buttons_usb_encoder/buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/io_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/phoniebox-buttons-usb-encoder.service.sample
  components/controls/buttons_usb_encoder/register_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh
  components/gpio_control/function_calls.py
Labels: enhancement

#1130 Web App settings for swipe or place rifd
  htdocs/inc.header.php
  htdocs/inc.setPlayerBehaviourRFID.php
  htdocs/lang/lang-en-UK.php
  htdocs/settings.php
  scripts/inc.writeGlobalConfig.sh
Labels: enhancement, php

#1235 Shortcuts volume commands of playout control
  scripts/playout_controls.sh
Labels: enhancement

#1255 Ensure ALSA is installed
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#1151 activation of shutdown button class in gpio_control
  components/gpio_control/GPIODevices/shutdown_button.py
  components/gpio_control/example_configs/gpio_settings_test.ini
  components/gpio_control/gpio_control.py
  components/gpio_control/test/gpio_settings_test.ini
  components/gpio_control/test/test_shutdown_button.py
Labels: bug, needs testing

#1174 Improve player.php performance
  htdocs/api/common.php
  htdocs/api/player.php
  scripts/inc.writeGlobalConfig.sh
  scripts/playout_controls.sh
Labels: enhancement

#1203 Spotify url conversion (http to mopidy format)
  htdocs/inc.processCheckCardEditRegister.php
  htdocs/lang/lang-de-DE.php
  htdocs/lang/lang-en-UK.php
  htdocs/lang/lang-nl-NL.php
Labels: enhancement

#1260 Webgui: Add more error handling in dir parsing
  htdocs/func.php
Labels: enhancement

#1269 feat: keep USB Button Encoder settings during update
  scripts/installscripts/buster-install-default-with-autohotspot.sh
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/stretch-install-default.sh
Labels: enhancement

#1230 Add CodeQL checks
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#1264 ShutdownVolumeReduction
  htdocs/inc.header.php
  htdocs/inc.setShutdownVolumeReduction.php
  htdocs/lang/lang-de-DE.php
  htdocs/lang/lang-en-UK.php
  htdocs/settings.php
  scripts/playout_controls.sh
  scripts/rfid_trigger_play.sh
  settings/rfid_trigger_play.conf.sample
Labels: enhancement
