Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2021-07, with the labels that each got.

#1452 Update README.md
  components/rfid-reader/RC522/README.md
Labels: enhancement

#1455 Future3/plugin --> Future3/webapp
  .gitignore
  resources/default-settings/jukebox.default.yaml
  resources/default-settings/logger.default.yaml
  src/jukebox/components/alsaif/__init__.py
  src/jukebox/components/alsaif/alsawave/__init__.py
  src/jukebox/components/jingle/__init__.py
  src/jukebox/components/jingle/jinglemp3/__init__.py
  src/jukebox/components/playermpd/__init__.py
  src/jukebox/components/rfid_reader/PhonieboxRfidReader.py
  src/jukebox/components/volume/__init__.py
  src/jukebox/jukebox/alsaif.py
  src/jukebox/jukebox/daemon.py
  src/jukebox/jukebox/plugs.py
  src/jukebox/jukebox/pubsub/__init__.py
  src/jukebox/jukebox/pubsub/server.py
  src/jukebox/jukebox/rpc/client.py
  src/jukebox/jukebox/rpc/server.py
  src/jukebox/misc/loggingext.py
  src/jukebox/run_jukebox.py
Labels: future3

#1457 Add lsof
  scripts/installscripts/buster-install-default-with-autohotspot.sh
  scripts/installscripts/buster-install-default.sh
Labels: bug
