Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2021-02, with the labels that each got.

#1285 fix: handle list of keycodes in buttons usb encoder
  components/controls/buttons_usb_encoder/README.md
  components/controls/buttons_usb_encoder/buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh
Labels: enhancement

#1291 FF and Rewind added to GPIO_SETTINGS.ini
  components/gpio_control/example_configs/gpio_settings.ini
Labels: enhancement

#1297 Add documentation Complete Install Guide
  docs/INSTALL-COMPLETE-GUIDE.md
Labels: enhancement

#1200 Webplayer: Time Played Interpolation, Improvements
  htdocs/inc.loadControls.php
  htdocs/js/jukebox.js
Labels: enhancement

#1122 implementing stop on removal for RC522
  scripts/daemon_rfid_reader.py
Labels: bug, python

#1302 RDM6300 addtional output formats, XOR Checksum
  scripts/Reader.py.experimental
Labels: enhancement

#1231 (bugfix) Fixes bug in folder tree, related to special chars
  htdocs/func.php
  htdocs/inc.viewFolderTree.php
  htdocs/index.php
Labels: bug

#1310 Update gpio_control.py
  components/gpio_control/gpio_control.py
Labels: bug

#1312 Fix missing import
  scripts/Reader.py.experimental
Labels: bug

#1262 Add bluetooth buttons and bluetooth headphone output toggle
  components/bluetooth-sink-switch/README.md
  components/bluetooth-sink-switch/bt-sink-switch.py
  components/bluetooth-sink-switch/install-bt-sink-switch.sh
  components/bluetooth-sink-switch/webif.png
  components/control/bluetooth-buttons/README.md
  components/control/bluetooth-buttons/bt-buttons-register-device.py
  components/control/bluetooth-buttons/bt-buttons.py
  components/control/bluetooth-buttons/install-bt-buttons.sh
  components/gpio_control/function_calls.py
  htdocs/ajax.getAudioSink.php
  htdocs/ajax.getBluetoothStatus.php
  htdocs/inc.bluetooth.php
  htdocs/lang/lang-de-DE.php
  htdocs/lang/lang-en-UK.php
  htdocs/lang/lang-nl-NL.php
  htdocs/settings.php
  misc/sampleconfigs/phoniebox-bt-buttons.service.sample
  scripts/playout_controls.sh
  scripts/rfid_trigger_play.sh
  scripts/startup-scripts.sh
  settings/rfid_trigger_play.conf.sample
Labels: enhancement

#1319 Fix unit test and remove Python 3.5 check
  .github/workflows/pythonpackage.yml
  components/gpio_control/test/test_gpio_control.py
Labels: bug
