Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2022-01, with the labels that each got.

#1701 Prevent socket timeout in MPD player interface
  src/jukebox/components/playermpd/__init__.py
Labels: future3

#1704 Typo - fixes #1693
  installation/routines/customize_options.sh
Labels: future3

#1705 Add access to Jukebox log files via web server
  docs/sphinx/userguide/troubleshooting.rst
  resources/default-settings/nginx.default
  resources/html/404.html
  resources/html/runsphinx.html
Labels: enhancement, future3

#1707 Match mpd.socket to mpd.service to be user local
  installation/routines/setup_mpd.sh
  resources/default-services/jukebox-daemon.service
Labels: bug, future3

#1712 IP, CPU Temp, Disk Usage
  src/jukebox/components/hostif/linux/__init__.py
  src/webapp/src/commands/index.js
  src/webapp/src/components/Settings/index.js
  src/webapp/src/components/Settings/status.js
  src/webapp/src/components/Settings/status/battery.js
  src/webapp/src/components/Settings/status/cpu-temp.js
  src/webapp/src/components/Settings/status/disk-usage.js
  src/webapp/src/components/Settings/status/index.js
  src/webapp/src/components/Settings/status/ip-address.js
  src/webapp/src/components/Settings/status/version.js
  src/webapp/src/config.js
Labels: future3

#1714 Bump webapp npm dependencies to latest version
  src/webapp/package-lock.json
  src/webapp/package.json
Labels: future3

#1700 Add new feature: Bluetooth sound device button listener
  docs/sphinx/api/api.rst
  docs/sphinx/api/controls.rst
  docs/sphinx/index.rst
  docs/sphinx/userguide/bluetooth_audio_buttons.rst
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/controls/__init__.py
  src/jukebox/components/controls/bluetooth_audio_buttons/README.rst
  src/jukebox/components/controls/bluetooth_audio_buttons/__init__.py
  src/jukebox/components/controls/common/evdev_listener.py
  src/jukebox/components/volume/__init__.py
Labels: enhancement, future3

#1718 Introduce Say my IP, long and short
  docker/jukebox.Dockerfile
  installation/routines/setup_jukebox_core.sh
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/hostif/linux/__init__.py
  src/jukebox/components/rpc_command_alias.py
  src/jukebox/jukebox/speaking_text/__init__.py
  src/webapp/src/commands/index.js
  src/webapp/src/components/Cards/controls/actions/host/index.js
  src/webapp/src/components/Cards/controls/actions/host/say-my-ip-options.js
  src/webapp/src/components/Settings/status/ip-address.js
  src/webapp/src/config.js
Labels: future3

#1720 [Webapp] Localization support + translation to German
  src/webapp/package-lock.json
  src/webapp/package.json
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/App.js
  src/webapp/src/components/Cards/controls/actions-controls.js
  src/webapp/src/components/Cards/controls/actions/host/say-my-ip-options.js
  src/webapp/src/components/Cards/controls/actions/play-music/index.js
  src/webapp/src/components/Cards/controls/actions/play-music/no-music-selected.js
  src/webapp/src/components/Cards/controls/actions/play-music/selected-single.js
  src/webapp/src/components/Cards/controls/actions/volume/slider-change-volume.js
  src/webapp/src/components/Cards/controls/command-selector.js
  src/webapp/src/components/Cards/controls/controls-selector.js
  src/webapp/src/components/Cards/controls/select-command-aliases.js
  src/webapp/src/components/Cards/dialogs/delete.js
  src/webapp/src/components/Cards/edit.js
  src/webapp/src/components/Cards/form.js
  src/webapp/src/components/Cards/list.js
  src/webapp/src/components/Cards/overview.js
  src/webapp/src/components/Cards/register.js
  src/webapp/src/components/Header/index.js
  src/webapp/src/components/Library/library-header.js
  src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js
  src/webapp/src/components/Library/lists/albums/album-list/index.js
  src/webapp/src/components/Library/lists/albums/song-list/index.js
  src/webapp/src/components/Library/lists/albums/song-list/song-list-controls.js
  src/webapp/src/components/Library/lists/albums/song-list/song-list-item.js
  src/webapp/src/components/Library/lists/folders/folder-list-item-back.js
  src/webapp/src/components/Library/lists/folders/folder-list-item.js
  src/webapp/src/components/Library/lists/folders/index.js
  src/webapp/src/components/Library/selector-header.js
  src/webapp/src/components/Navigation/index.js
  src/webapp/src/components/Player/controls.js
  src/webapp/src/components/Player/cover.js
  src/webapp/src/components/Player/display.js
  src/webapp/src/components/Player/seekbar.js
  src/webapp/src/components/Player/volume.js
  src/webapp/src/components/Settings/autohotspot.js
  src/webapp/src/components/Settings/autoshutdown.js
  src/webapp/src/components/Settings/dialogs/reboot.js
  src/webapp/src/components/Settings/dialogs/shutdown.js
  src/webapp/src/components/Settings/secondswipe.js
  src/webapp/src/components/Settings/status/battery.js
  src/webapp/src/components/Settings/status/cpu-temp.js
  src/webapp/src/components/Settings/status/disk-usage.js
  src/webapp/src/components/Settings/status/index.js
  src/webapp/src/components/Settings/status/ip-address.js
  src/webapp/src/components/Settings/status/version.js
  src/webapp/src/components/Settings/systemcontrols.js
  src/webapp/src/components/Settings/volume.js
  src/webapp/src/config.js
  src/webapp/src/i18n.js
  src/webapp/src/index.js
Labels: future3

#1725 Enable timers in webapp
  src/jukebox/components/rpc_command_alias.py
  src/jukebox/jukebox/multitimer.py
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/commands/index.js
  src/webapp/src/components/Cards/controls/actions/timers/index.js
  src/webapp/src/components/Cards/controls/actions/timers/slider-set-timer.js
  src/webapp/src/components/Cards/controls/controls-selector.js
  src/webapp/src/components/Settings/autohotspot.js
  src/webapp/src/components/Settings/autoshutdown.js
  src/webapp/src/components/Settings/index.js
  src/webapp/src/components/Settings/timers/index.js
  src/webapp/src/components/Settings/timers/timer.js
  src/webapp/src/components/Settings/volume.js
  src/webapp/src/components/custom/index.js
  src/webapp/src/components/general/Countdown.js
  src/webapp/src/components/general/SliderTimer.js
  src/webapp/src/components/general/SwitchWithLoader.js
  src/webapp/src/components/general/index.js
  src/webapp/src/config.js
Labels: future3

#1726 Allow to change audio outputs in webapp
  src/jukebox/components/volume/__init__.py
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/commands/index.js
  src/webapp/src/components/Cards/controls/actions/audio/index.js
  src/webapp/src/components/Cards/controls/actions/audio/slider-change-volume.js
  src/webapp/src/components/Cards/controls/actions/host/say-my-ip-options.js
  src/webapp/src/components/Cards/controls/controls-selector.js
  src/webapp/src/components/Settings/audio/index.js
  src/webapp/src/components/Settings/audio/max-volume.js
  src/webapp/src/components/Settings/audio/outputs.js
  src/webapp/src/components/Settings/index.js
  src/webapp/src/config.js
Labels: future3

#1730 Rotary alias fix
  src/jukebox/components/gpio/gpio_rpi/README.rst
Labels: future3
