Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2022-12, with the labels that each got.

#1933 Updated Python versions to use for CI
  .github/workflows/pythonpackage.yml
Labels: enhancement, python

#1784 Update README.rst
  src/jukebox/components/rfid/hardware/rc522_spi/README.rst
Labels: enhancement, future3

#1836 Update 'GPIO Recipes' for power button
  src/jukebox/components/gpio/gpioz/README.rst
Labels: documentation, future3

#1880 Package cleanup
  installation/routines/setup_jukebox_core.sh
  requirements.txt
  src/jukebox/components/music_cover_art/__init__.py
Labels: future3

#1908 Correct paths in configuration.rst
  docs/sphinx/userguide/configuration.rst
Labels: documentation, future3

#1823 Create php.yml
  .github/workflows/php.yml
  composer.json
  composer.lock
  tests/htdocs/TrackEditTest.php
  tests/htdocs/api/PlayListTest.php
  tests/htdocs/api/PlayerTest.php
Labels: enhancement, php
