Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2022-04, with the labels that each got.

#1800 (docs) fixed typos in audio.rst
  docs/sphinx/userguide/audio.rst
Labels: documentation, future3

#1798 Fix newline/comment generation in run_configure_audio
  src/jukebox/run_configure_audio.py
Labels: bug, future3

#1796 (docs)fixed typo in pinout doc for rc522_spi
  src/jukebox/components/rfid/hardware/rc522_spi/README.rst
Labels: future3
