Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2022-02, with the labels that each got.

#1719 Shift GPIOs towards GPIOZero
  docs/sphinx/api/api.rst
  docs/sphinx/api/callingback.rst
  docs/sphinx/api/gpioz/connector.rst
  docs/sphinx/api/gpioz/converter.rst
  docs/sphinx/api/gpioz/gpioz.rst
  docs/sphinx/api/gpioz/input_devices.rst
  docs/sphinx/api/gpioz/output_devices.rst
  docs/sphinx/api/volume.rst
  docs/sphinx/conf.py
  docs/sphinx/gpio/gpio_rpi.rst
  docs/sphinx/index.rst
  docs/sphinx/requirements.txt
  docs/sphinx/rfid/mock_reader.png
  docs/sphinx/userguide/gpioz.rst
  docs/sphinx/userguide/mock_gpio.png
  docs/sphinx/userguide/rpc_command_alias_reference.rst
  docs/sphinx/userguide/rpc_command_reference.rst
  installation/routines/setup_jukebox_core.sh
  requirements.txt
  resources/default-settings/gpioz.example.yaml
  resources/default-settings/jukebox.default.yaml
  run_sphinx.sh
  src/jukebox/components/controls/bluetooth_audio_buttons/__init__.py
  src/jukebox/components/gpio/gpio_rpi/README.rst
  src/jukebox/components/gpio/gpio_rpi/__init__.py
  src/jukebox/components/gpio/gpio_rpi/button.py
  src/jukebox/components/gpio/gpio_rpi/port_out.py
  src/jukebox/components/gpio/gpio_rpi/rotary_encoder.py
  src/jukebox/components/gpio/gpio_simulator/__init__.py
  src/jukebox/components/gpio/gpioz/README.rst
  src/jukebox/components/gpio/gpioz/core/converter.py
  src/jukebox/components/gpio/gpioz/core/input_devices.py
  src/jukebox/components/gpio/gpioz/core/mock.py
  src/jukebox/components/gpio/gpioz/core/output_devices.py
  src/jukebox/components/gpio/gpioz/plugin/__init__.py
  src/jukebox/components/gpio/gpioz/plugin/connectivity.py
  src/jukebox/components/rfid/configure/__init__.py
  src/jukebox/components/rfid/hardware/fake_reader_gui/README.rst
  src/jukebox/components/rfid/hardware/fake_reader_gui/fake_reader_gui.py
  src/jukebox/components/rfid/hardware/fake_reader_gui/gpioz_gui_addon.py
  src/jukebox/components/rfid/pinaction/rpi/__init__.py
  src/jukebox/components/rfid/reader/__init__.py
  src/jukebox/components/volume/__init__.py
  src/jukebox/jukebox/callingback.py
  src/jukebox/jukebox/daemon.py
  src/jukebox/jukebox/multitimer.py
  src/jukebox/jukebox/plugs.py
  src/jukebox/jukebox/utils.py
  src/jukebox/misc/__init__.py
  test/gpioz/test_twinbutton.py
Labels: future3

#1743 Add equalizer and mono down-mixer as configuration option
  docs/sphinx/userguide/audio.rst
  docs/sphinx/userguide/system.rst
  installation/routines/setup_jukebox_core.sh
  resources/default-settings/pulseaudio.default.pa
  src/jukebox/run_configure_audio.py
Labels: future3

#1747 Improve MPD install routine
  installation/routines/setup_mpd.sh
Labels: future3

#1748 Always fetch git release tags
  installation/routines/setup_git.sh
  src/jukebox/jukebox/utils.py
Labels: future3

#1752 Language independent memory size deduction
  src/webapp/run_rebuild.sh
Labels: future3

#1751 AsyncIO MPD player backend
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/playern/backends/interfacing_mpd.py
  src/jukebox/components/playern/core/__init__.py
  src/jukebox/components/playern/plugin/__init__.py
  src/jukebox/components/players/player_main.py
Labels: future3

#1749 Add exit_on_error handler for install routines
  installation/includes/05_finish.sh
  installation/install-jukebox.sh
  installation/routines/customize_options.sh
  installation/routines/setup_git.sh
  installation/routines/setup_jukebox_core.sh
  installation/routines/setup_jukebox_webapp.sh
  installation/routines/setup_rfid_reader.sh
Labels: future3

#1753 (packaging) Remove nanotime dependency
  requirements.txt
  src/jukebox/jukebox/rpc/server.py
Labels: future3

#1755 Check for 32 bit OS version before installing
  installation/includes/02_helpers.sh
  installation/routines/install.sh
Labels: future3

#1757 Move gpioZ to gpio in user configuration
  docs/sphinx/userguide/rpc_command_alias_reference.rst
  docs/sphinx/userguide/rpc_command_reference.rst
  resources/default-settings/gpio.example.yaml
  resources/default-settings/gpioz.example.yaml
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/gpio/gpioz/README.rst
Labels: future3

#1759 Implement folder and album playback in Async MPD Interface
  src/jukebox/components/playern/backends/interfacing_mpd.py
  src/jukebox/components/playern/core/__init__.py
Labels: future3

#1756 Readme update for future3 3.2 Beta release
  README.md
Labels: future3

#1761 Spotify Backend
  resources/default-settings/jukebox.default.yaml
  resources/default-settings/spotify.config.toml
  resources/default-settings/spotify_collection.example.yaml
  shared/audio/.gitkeep
  src/jukebox/components/playern/backends/mpd/interfacing_mpd.py
  src/jukebox/components/playern/backends/spotify/http_client.py
  src/jukebox/components/playern/backends/spotify/interfacing_spotify.py
  src/jukebox/components/playern/backends/spotify/ws_client.py
  src/jukebox/components/playern/core/player_status.py
  src/jukebox/components/playern/plugin/__init__.py
  src/jukebox/components/players/player_main.py
Labels: future3

#1692 #1309, #1451 Fixes missing title and cover for spotify playlists by adding user-agent
  htdocs/inc.viewFolderTree.php
Labels: enhancement

#1496 Publish "card swiped" event via MQTT
  components/smart-home-automation/MQTT-protocol/README.md
  components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
  components/smart-home-automation/MQTT-protocol/requirements.txt
Labels: enhancement

#1543 Remove hardcoded homedir in install scritp
  .github/workflows/dockerimage.yml
  ci/Dockerfile.buster.test_install_altuser.amd64
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/run_installation_tests2_altuser.sh
  scripts/installscripts/tests/run_installation_tests3_altuser.sh
  scripts/installscripts/tests/run_installation_tests_altuser.sh
  scripts/installscripts/tests/test_installation_altuser.sh
Labels: enhancement

#1521 adjust playerpauseforce
  scripts/playout_controls.sh
Labels: bug

#1517 Add sustainability notes
  README.md
Labels: documentation

#1511 Fix samplecfg for GPIO component
  misc/sampleconfigs/gpio_settings.ini.sample
Labels: bug

#1506 quickfix idle-watchdog with amixer
  scripts/idle-watchdog.sh
Labels: bug

#1493 (docs) Fix Link in README.md
  README.md
Labels: enhancement, documentation
