Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2022-03, with the labels that each got.

#1789 fix(install): updates the URL and adds missing key
  scripts/installscripts/buster-install-default.sh
Labels: bug, spotify edition

#1702 Reader.py: split line read from deviceName.txt
  scripts/Reader.py.experimental
Labels: enhancement

#1525 (docs) GPIO-Documentation in /docs is deprecated
  docs/GPIO-BUTTONS.md
Labels: documentation

#1791 Fix git protocol for pip
  components/rfid-reader/RC522/requirements.txt
  requirements.txt
Labels: bug, installation

#1793 Add french language to our favorite jukebox
  htdocs/lang/lang-fr-FR.php
Labels: enhancement

#1792 fix(install): mopidy for spotify install
  scripts/installscripts/buster-install-default-with-autohotspot.sh
  scripts/installscripts/buster-install-default.sh
Labels: bug, installation
