Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-05, with the labels that each got.

#2017 Fix #1848
  components/smart-home-automation/MQTT-protocol/README.md
Labels: enhancement, documentation

#2009 future3 - Feature "sync shared"
  docs/sphinx/index.rst
  docs/sphinx/userguide/sync_rfidcards.rst
  resources/default-settings/jukebox.default.yaml
  resources/default-settings/sync_rfidcards.default.yaml
  src/jukebox/components/gpio/gpioz/plugin/connectivity.py
  src/jukebox/components/playermpd/__init__.py
  src/jukebox/components/playermpd/playcontentcallback.py
  src/jukebox/components/rfid/reader/__init__.py
  src/jukebox/components/rpc_command_alias.py
  src/jukebox/components/synchronisation/__init__.py
  src/jukebox/components/synchronisation/rfidcards/__init__.py
  src/jukebox/components/synchronisation/syncutils.py
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/commands/index.js
  src/webapp/src/components/Cards/controls/actions/synchronisation/index.js
  src/webapp/src/components/Cards/controls/actions/synchronisation/rfidcards/change-on-rfid-scan-options.js
  src/webapp/src/components/Cards/controls/controls-selector.js
  src/webapp/src/config.js
Labels: future3

#2032 add Coverage action
  .github/workflows/pythonpackage.yml
Labels: enhancement, python
