Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-12, with the labels that each got.

#2128 Bookworm Web Interface 403
  htdocs/manageFilesFolders.php
  misc/sampleconfigs/lighttpd.conf.buster-default.sample
  scripts/installscripts/install-jukebox.sh
Labels: bug

#2119 Add installation checks + CI Workflow
  .dockerignore
  .github/workflows/test_docker_debian_codename_sub_v3.yml
  .github/workflows/test_docker_debian_v3.yml
  README.md
  ci/ci-debian.Dockerfile
  ci/installation/run_install_common.sh
  ci/installation/run_install_faststartup.sh
  ci/installation/run_install_user_not_pi.sh
  ci/installation/run_install_webapp_download.sh
  ci/installation/run_install_webapp_local.sh
  installation/README.md
  installation/includes/00_constants.sh
  installation/includes/01_default_config.sh
  installation/includes/02_helpers.sh
  installation/includes/04_cleanup.sh
  installation/includes/05_finish.sh
  installation/install-jukebox.sh
  installation/routines/customize_options.sh
  installation/routines/install.sh
  installation/routines/optimize_boot_time.sh
  installation/routines/set_raspi_config.sh
  installation/routines/set_ssh_qos.sh
  installation/routines/setup_autohotspot.sh
  installation/routines/setup_git.sh
  installation/routines/setup_jukebox_core.sh
  installation/routines/setup_jukebox_webapp.sh
  installation/routines/setup_kiosk_mode.sh
  installation/routines/setup_mpd.sh
  installation/routines/setup_rfid_reader.sh
  installation/routines/setup_samba.sh
  installation/routines/update_raspi_os.sh
  packages-core.txt
  requirements.txt
  src/jukebox/components/rfid/configure/__init__.py
  src/jukebox/components/rfid/reader/__init__.py
Labels: enhancement, future3

#2132 future3 - allow custom username
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/workflows/test_docker_debian_codename_sub_v3.yml
  CONTRIBUTING.md
  ci/ci-debian.Dockerfile
  ci/installation/run_install_user_not_pi.sh
  documentation/builders/autohotspot.md
  documentation/builders/installation.md
  documentation/builders/system.md
  documentation/developers/known-issues.md
  installation/install-jukebox.sh
  installation/routines/setup_autohotspot.sh
  installation/routines/setup_jukebox_webapp.sh
  resources/autohotspot/autohotspot.timer
  resources/default-settings/jukebox.default.yaml
  resources/default-settings/nginx.default
  src/webapp/src/config.js
Labels: enhancement, future3

#2143 [Bugfix] Webapp allows to assign single song to card
  docker/docker-compose.yml
  src/jukebox/components/playermpd/__init__.py
  src/webapp/src/components/Library/lists/index.js
Labels: future3

#2147 [Docs] Inform about Python venv
  documentation/developers/README.md
  documentation/developers/development-environment.md
  documentation/developers/pyhton.md
Labels: future3

#2146 Add running pytest to GitHub action
  .flake8
  .github/workflows/pythonpackage_future3.yml
  requirements.txt
  run_pytest.sh
  src/jukebox/misc/loggingext.py
Labels: enhancement, future3

#2151 some documentation updates
  documentation/builders/audio.md
  documentation/builders/concepts.md
  documentation/builders/configuration.md
  documentation/builders/rpc-commands.md
  documentation/builders/system.md
  documentation/builders/troubleshooting.md
  documentation/builders/update.md
  documentation/developers/coreapps.md
  documentation/developers/developer-issues.md
  documentation/developers/docker.md
  documentation/developers/rfid/basics.md
  documentation/developers/rfid/genericusb.md
  documentation/developers/rfid/mfrc522_spi.md
  documentation/developers/rfid/template_reader.md
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/rfid/hardware/fake_reader_gui/requirements.txt
  src/jukebox/components/rfid/hardware/pn532_i2c_py532/requirements.txt
  src/jukebox/components/rfid/hardware/rdm6300_serial/requirements.txt
Labels: documentation, future3

#2149 Minor doc improvements
  documentation/builders/audio.md
  documentation/builders/installation.md
  documentation/developers/pyhton.md
Labels: documentation, future3

#2153 Add coverage badge
  README.md
Labels: future3

#2158 Ignore test directories for coverage
  .coveragerc
  .github/workflows/pythonpackage_future3.yml
  src/jukebox/misc/loggingext.py
Labels: enhancement, future3

#1857 Adapt pbc.c to current json rpc spec
  src/cli_client/pbc.c
Labels: enhancement, future3

#2162 Add docs for command line client for RPC
  documentation/builders/README.md
  documentation/builders/cli-client.md
  documentation/builders/rpc-commands.md
  documentation/builders/system.md
  documentation/developers/README.md
  documentation/developers/coreapps.md
  documentation/developers/libzmq.md
  documentation/developers/pyhton.md
  src/cli_client/pbc.c
Labels: documentation, future3

#2166 Improve the run_rpc_tool script
  .flake8
  documentation/developers/coreapps.md
  src/jukebox/run_rpc_tool.py
Labels: enhancement, future3

#2173 Improve Docs: Fix GPIO and add WSL
  documentation/builders/README.md
  documentation/builders/audio.md
  documentation/builders/card-database.md
  documentation/builders/configuration.md
  documentation/builders/gpio.md
  documentation/builders/installation.md
  documentation/builders/troubleshooting.md
  documentation/developers/coreapps.md
  documentation/developers/developer-issues.md
  documentation/developers/development-environment.md
  documentation/developers/docker.md
  documentation/developers/known-issues.md
  documentation/developers/status.md
Labels: documentation, future3

#2175 Update Readme for next release
  .github/workflows/test_docker_debian.yml
  README.md
Labels: documentation

#2177 Cover Art with Cache
  .gitignore
  docker/docker-compose.yml
  requirements.txt
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/music_cover_art/__init__.py
  src/jukebox/components/playermpd/__init__.py
  src/jukebox/components/playermpd/coverart_cache_manager.py
  src/webapp/public/cover-cache/.gitkeep
  src/webapp/src/commands/index.js
  src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js
  src/webapp/src/components/Player/cover.js
  src/webapp/src/components/Player/index.js
Labels: future3

#2178 Improve docs
  documentation/README.md
  documentation/builders/gpio.md
  documentation/builders/rpc-commands.md
  documentation/builders/system.md
  documentation/builders/troubleshooting.md
  documentation/developers/rfid/basics.md
  documentation/developers/rfid/mfrc522_spi.md
  documentation/developers/rfid/mock_reader.md
  documentation/developers/rfid/pn532_i2c.md
  documentation/developers/rfid/template_reader.md
Labels: documentation, future3

#2176 Update Pulseaudio docs for Docker on Mac
  docker/jukebox.Dockerfile
  documentation/developers/docker.md
Labels: documentation, future3

#2182 Activate codeql analysis
  .github/workflows/codeql-analysis_v3.yml
Labels: future3
