Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-03, with the labels that each got.

#1953 add patch for serializable
  .github/workflows/php.yml
  composer.json
  composer.lock
Labels: enhancement, php

#1980 Use existing actions for Docker GitHub Action
  .github/workflows/dockerimage.yml
Labels: enhancement

#1968 removed "is set" check (#1967)
  scripts/rfid_trigger_play.sh
Labels: bug, bash

#1949 Fix docs for 2.x
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  INSTALL
  README.md
  docs/FIRMWARE_UPDATE.md
  docs/GPIO-BUTTONS.md
  docs/INSTALL-COMPLETE-GUIDE.md
  docs/PHONIEBOX_ReadOnly.md
  docs/UPGRADE.md
  docs/WLAN-ACCESS-POINT.md
Labels: enhancement, documentation

#1985 Close devices
  scripts/RegisterDevice.py
Labels: enhancement

#1978 Feature "sync shared"
  .gitignore
  components/synchronisation/sync-shared/README.md
  components/synchronisation/sync-shared/change-configuration.sh
  components/synchronisation/sync-shared/install-sync-shared.sh
  components/synchronisation/sync-shared/settings/sync-shared.conf.sample
  components/synchronisation/sync-shared/sync-shared.sh
  htdocs/inc.header.php
  scripts/playout_controls.sh
  scripts/rfid_trigger_play.sh
  settings/debugLogging.conf.sample
  settings/rfid_trigger_play.conf.sample
Labels: enhancement, bash

#1986 Add bullseye Dockerfile
  .github/workflows/dockerimage.yml
  ci/Dockerfile.bullseye.test_install.amd64
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#1988 Test files not used anymore
  scripts/test/mockedGPIO.py
  scripts/test/test_TwoButtonControl.py
Labels: enhancement, python

#1996 Update python version matrix
  .github/workflows/pythonpackage.yml
Labels: enhancement

#1990 Add new python dependecies (setuptools, wheel)
  scripts/installscripts/buster-install-default-with-autohotspot.sh
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/test_installation.sh
  scripts/installscripts/tests/test_installation_altuser.sh
Labels: bug
