Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-01, with the labels that each got.

#1950 typos in docs
  docs/sphinx/primer.rst
Labels: documentation, future3

#1954 Fix count in flake8 config
  .flake8
Labels: bug, python, future3

#1939 Remove Gmusic
  README.md
  requirements-gmusic.txt
Labels: streaming service

#1935 Delete scripts/python-phoniebox directory
  scripts/python-phoniebox/ConfigParserExtended.py
  scripts/python-phoniebox/LICENSE
  scripts/python-phoniebox/Phoniebox.py
  scripts/python-phoniebox/PhonieboxConfigChanger.py
  scripts/python-phoniebox/PhonieboxDaemon.py
  scripts/python-phoniebox/README.md
  scripts/python-phoniebox/RawConfigParserExtended.py
  scripts/python-phoniebox/Reader.py
  scripts/python-phoniebox/__init__.py
  scripts/python-phoniebox/deviceName.txt
  scripts/python-phoniebox/helpers_unused_atm/__init__.py
  scripts/python-phoniebox/helpers_unused_atm/helpers.py
  scripts/python-phoniebox/phoniebox.conf
Labels: enhancement

#1961 Clarify when to open an issue or a discussion
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement, documentation
