Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-10, with the labels that each got.

#2077 future3: Abort installation if user is not "pi"
  .github/workflows/dockerimage.yml
  .github/workflows/pythonpackage.yml
  installation/install-jukebox.sh
Labels: enhancement, future3

#2076 Abort installation if user is not "pi"
  .github/workflows/docker_bullseye.yml
  .github/workflows/docker_bullseye_altuser.yml
  .github/workflows/docker_buster.yml
  ci/Dockerfile.bullseye.test_install.amd64
  ci/Dockerfile.bullseye.test_install.armv7
  ci/Dockerfile.bullseye.test_install_altuser.armv7
  ci/Dockerfile.buster.amd64
  ci/Dockerfile.buster.armv7
  ci/Dockerfile.buster.test_install.armv7
  scripts/installscripts/buster-install-default-with-autohotspot.sh
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/run_installation_tests.sh
  scripts/installscripts/tests/run_installation_tests2.sh
  scripts/installscripts/tests/run_installation_tests2_altuser.sh
  scripts/installscripts/tests/run_installation_tests3.sh
  scripts/installscripts/tests/run_installation_tests3_altuser.sh
  scripts/installscripts/tests/run_installation_tests_altuser.sh
  scripts/installscripts/tests/test_installation.sh
  scripts/installscripts/tests/test_installation_altuser.sh
Labels: enhancement

#2075 fix unavailable repo for pi-rc522
  docs/sphinx/requirements.txt
  src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt
Labels: bug, ext dependency, future3

#2078 Fix rc-522 dependency
  components/rfid-reader/RC522/requirements.txt
Labels: bug, ext dependency

#2083 Update Status Badge
  README.md
Labels: enhancement
