Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-11, with the labels that each got.

#2091 add autohotspot config checks
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#2096 Fix pyzmq installation from source with drafts support
  installation/routines/setup_jukebox_core.sh
Labels: enhancement, future3

#2097 Remove unused _jukebox_core_download_prebuilt_pyzmq
  installation/routines/setup_jukebox_core.sh
Labels: enhancement, future3

#2084 Make changes for Raspberry Pi OS Bookworm
  .github/workflows/pythonpackage.yml
  .github/workflows/test_docker_debian.yml
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#2092 Further Optimizations
  .github/workflows/test_docker_debian_codename_sub.yml
  README.md
  ci/Dockerfile.debian
  packages-autohotspot.txt
  packages-raspberrypi.txt
  packages-spotify.txt
  packages.txt
  requirements.txt
  scripts/helperscripts/setup_autohotspot.sh
  scripts/installscripts/buster-install-default.sh
  scripts/installscripts/tests/run_installation_tests.sh
  scripts/installscripts/tests/run_installation_tests2.sh
  scripts/installscripts/tests/run_installation_tests3.sh
  scripts/installscripts/tests/test_installation.sh
Labels: enhancement

#2102 Fix link to feature status
  documentation/README.md
  documentation/content/developers/status.md
Labels: future3

#2100 Fix future3 installation for bookworm
  installation/routines/setup_jukebox_core.sh
  installation/routines/setup_jukebox_webapp.sh
Labels: enhancement, installation, ext dependency, future3

#2105 fix some more doc links
  README.md
  documentation/content/developers/README.md
  documentation/content/developers/coreapps.md
  documentation/content/developers/development-environment.md
  documentation/content/developers/docker.md
  documentation/content/userguide/README.md
  documentation/content/userguide/audio.md
  documentation/content/userguide/concepts.md
  documentation/content/userguide/configuration.md
  documentation/content/userguide/installation.md
  documentation/content/userguide/system.md
Labels: documentation, future3

#2107 fix #2101
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
Labels: future3

#2103 Future3/update dependencies
  .githooks/post-merge
  docker/armv7/jukebox.Dockerfile
  docker/docker-compose.yml
  docker/jukebox.Dockerfile
  docker/webapp.Dockerfile
  documentation/content/developers/development-environment.md
  documentation/content/userguide/installation.md
  installation/includes/03_welcome.sh
  installation/install-jukebox.sh
  installation/routines/customize_options.sh
  installation/routines/set_raspi_config.sh
  installation/routines/setup_jukebox_core.sh
  installation/routines/setup_jukebox_webapp.sh
  installation/routines/setup_rfid_reader.sh
  resources/default-services/jukebox-daemon.service
  src/jukebox/components/rfid/configure/__init__.py
  src/jukebox/components/rfid/hardware/pn532_i2c_py532/requirements.txt
  src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt
  src/jukebox/jukebox/NvManager.py
  src/jukebox/jukebox/playlistgenerator.py
  src/jukebox/run_configure_audio.py
  src/jukebox/run_jukebox.py
  src/jukebox/run_publicity_sniffer.py
  src/jukebox/run_register_rfid_reader.py
  src/jukebox/run_rpc_tool.py
  src/webapp/package-lock.json
  src/webapp/package.json
Labels: future3

#2110 rename install script to "install-jukebox.sh"
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_template.md
  ci/Dockerfile.debian
  ci/README.md
  scripts/installscripts/install-jukebox.sh
  scripts/installscripts/tests/run_installation_tests.sh
  scripts/installscripts/tests/run_installation_tests2.sh
  scripts/installscripts/tests/run_installation_tests3.sh
Labels: enhancement, installation

#2106 More links fixed
  documentation/content/developers/rfid/README.md
  documentation/content/developers/rfid/basics.md
  documentation/content/developers/rfid/genericusb.md
  documentation/content/developers/rfid/mfrc522_spi.md
  documentation/content/developers/rfid/template_reader.md
  src/jukebox/components/rfid/hardware/fake_reader_gui/README.md
  src/jukebox/components/rfid/hardware/fake_reader_gui/README.rst
  src/jukebox/components/rfid/hardware/generic_usb/README.md
  src/jukebox/components/rfid/hardware/generic_usb/README.rst
  src/jukebox/components/rfid/hardware/pn532_i2c_py532/README.md
  src/jukebox/components/rfid/hardware/pn532_i2c_py532/README.rst
  src/jukebox/components/rfid/hardware/rc522_spi/README.md
  src/jukebox/components/rfid/hardware/rc522_spi/README.rst
  src/jukebox/components/rfid/hardware/rdm6300_serial/README.md
  src/jukebox/components/rfid/hardware/rdm6300_serial/README.rst
Labels: documentation, future3

#2113 Keep docs for template reader at src and fix markdown warnings
  CODE_OF_CONDUCT.md
  documentation/content/developers/developer-issues.md
  documentation/content/developers/development-environment.md
  documentation/content/developers/docker.md
  documentation/content/developers/rfid/README.md
  documentation/content/developers/rfid/mfrc522_spi.md
  documentation/content/developers/rfid/template_reader.md
  documentation/content/developers/status.md
  documentation/content/userguide/README.md
  documentation/content/userguide/audio.md
  documentation/content/userguide/autohotspot.md
  documentation/content/userguide/installation.md
Labels: documentation, future3

#2111 Future3 fix venv usage
  .github/workflows/pythonpackage_future3.yml
  docker/armv7/jukebox.Dockerfile
  docker/jukebox.Dockerfile
  documentation/content/developers/development-environment.md
  installation/includes/00_constants.sh
  installation/routines/setup_jukebox_core.sh
  installation/routines/setup_jukebox_webapp.sh
  installation/routines/setup_mpd.sh
  requirements.txt
  resources/default-services/jukebox-daemon.service
  src/jukebox/components/rfid/configure/__init__.py
  src/jukebox/jukebox/multitimer.py
Labels: enhancement, future3

#2114 fix docker description for windows
  documentation/content/developers/docker.md
Labels: documentation, future3

#2109 Cleanup installation messages
  installation/includes/02_helpers.sh
  installation/includes/03_welcome.sh
  installation/includes/05_finish.sh
  installation/routines/customize_options.sh
  installation/routines/install.sh
  installation/routines/optimize_boot_time.sh
  installation/routines/setup_mpd.sh
  src/jukebox/components/hostif/linux/__init__.py
  src/webapp/public/locales/de/translation.json
Labels: enhancement, installation, future3

#2122 Update some links in the documentation
  README.md
  documentation/README.md
  documentation/content/builders/README.md
  documentation/content/builders/audio.md
  documentation/content/builders/autohotspot.md
  documentation/content/builders/bluetooth-audio-buttons.md
  documentation/content/builders/card-database.md
  documentation/content/builders/concepts.md
  documentation/content/builders/configuration.md
  documentation/content/builders/installation.md
  documentation/content/builders/mock_gpio.png
  documentation/content/builders/rfid.md
  documentation/content/builders/system.md
  documentation/content/builders/troubleshooting.md
  documentation/content/builders/update.md
  documentation/content/developers/coreapps.md
  documentation/content/developers/development-environment.md
  documentation/content/developers/rfid/basics.md
  documentation/content/developers/rfid/mock_reader.md
  documentation/content/developers/status.md
Labels: future3

#2127 Future3/documentation
  documentation/README.md
  documentation/builders/README.md
  documentation/builders/audio.md
  documentation/builders/card-database.md
  documentation/builders/concepts.md
  documentation/builders/configuration.md
  documentation/builders/rpc-commands.md
  documentation/developers/coreapps.md
  documentation/developers/developer-issues.md
  documentation/developers/rfid/basics.md
  documentation/developers/rfid/genericusb.md
  documentation/developers/rfid/mock_reader.md
  documentation/developers/rfid/template_reader.md
  src/jukebox/components/rfid/hardware/fake_reader_gui/README.md
  src/jukebox/components/rfid/hardware/generic_usb/README.md
  src/jukebox/components/rfid/hardware/pn532_i2c_py532/README.md
  src/jukebox/components/rfid/hardware/rc522_spi/README.md
  src/jukebox/components/rfid/hardware/rdm6300_serial/README.md
  src/jukebox/components/rfid/hardware/template_new_reader/README.md
Labels: future3

#2126 future3 V3.3 - reference webapp build
  installation/routines/setup_jukebox_webapp.sh
  src/jukebox/jukebox/version.py
Labels: future3
