Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2023-04, with the labels that each got.

#1952 a few more typos and wordings
  docs/sphinx/featurelist.rst
  docs/sphinx/install.rst
  docs/sphinx/issues.rst
  docs/sphinx/migration.rst
  docs/sphinx/primer.rst
Labels: documentation, future3

#1928 Use env variables for pyzmq
  installation/routines/setup_jukebox_core.sh
Labels: enhancement, future3

#1989 Fix Workflow Actions flake8 (future3)
  .github/workflows/pythonpackage_future3.yml
  requirements.txt
  src/jukebox/components/battery_monitor/BatteryMonitorBase.py
  src/jukebox/jukebox/playlistgenerator.py
Labels: enhancement, future3

#2010 update webapp dependencies
  src/webapp/package-lock.json
  src/webapp/package.json
Labels: future3
