Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2024-04, with the labels that each got.

#2307 fix: Build libzmq locally to work on all host types
  docker/Dockerfile.jukebox
  docker/Dockerfile.libzmq
  docker/Dockerfile.mpd
  docker/Dockerfile.webapp
  docker/config/docker.mpd.conf
  docker/config/docker.pulse.mpd.conf
  docker/docker-compose.linux.yml
  docker/docker-compose.yml
  documentation/developers/docker.md
  installation/routines/setup_jukebox_core.sh
Labels: needs testing, future3

#2323 Fix PlayerMPD.rewind to start with the first song (future3)
  src/jukebox/components/playermpd/__init__.py
Labels: bug, future3

#2320 Add Python 3.12 to Action
  .flake8
  .github/workflows/pythonpackage_future3.yml
  src/jukebox/components/controls/common/evdev_listener.py
  src/jukebox/components/volume/__init__.py
  src/jukebox/run_configure_audio.py
Labels: enhancement, python, future3

#2325 Fix CoverartCacheManager
  requirements.txt
  src/jukebox/components/playermpd/__init__.py
  src/jukebox/components/playermpd/coverart_cache_manager.py
  src/jukebox/components/rpc_command_alias.py
  src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js
Labels: enhancement, future3

#2319 Remove Buster Support
  .github/workflows/pythonpackage.yml
  .github/workflows/test_docker_debian.yml
  CONTRIBUTING.md
  components/smart-home-automation/MQTT-protocol/README.md
  components/smart-home-automation/MQTT-protocol/phoniebox-mqtt-client.service-default.sample
  misc/sampleconfigs/15-fastcgi-php.conf-default.sample
  misc/sampleconfigs/deviceName.txt.stretch-default.sample
  misc/sampleconfigs/dhcpcd.conf-default-noHotspot.sample
  misc/sampleconfigs/lighttpd.conf-default.sample
  misc/sampleconfigs/phoniebox-activate-amplifier.service-default.sample
  misc/sampleconfigs/phoniebox-rfid-reader.service-default.sample
  misc/sampleconfigs/phoniebox-startup-scripts.service-default.sample
  misc/sampleconfigs/phoniebox-startup-sound.service.stretch-default.sample
  misc/sampleconfigs/php.ini-default.sample
  misc/sampleconfigs/smb.conf-default.sample
  misc/sampleconfigs/sudoers-default.sample
  scripts/installscripts/install-jukebox.sh
Labels: installation, legacy_v2

#2333 README: Fix typo RC422 -> RC522
  README.md
Labels: documentation, legacy_v2

#2334 maint: Update actions
  .github/workflows/codeql-analysis_v3.yml
  .github/workflows/pythonpackage_future3.yml
Labels: future3

#2326 Fix PlayerMPD.prev/next() when stopped
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/playermpd/__init__.py
  src/jukebox/jukebox/utils.py
Labels: bug, future3

#2336 doc: fix typo in docker.md
  documentation/developers/docker.md
Labels: documentation, future3

#2315 Spotify fixes
  README.md
  components/bluetooth-sink-switch/README.md
  htdocs/inc.processCheckCardEditRegister.php
  htdocs/lang/lang-de-DE.php
  htdocs/lang/lang-en-UK.php
  htdocs/lang/lang-fr-FR.php
  htdocs/lang/lang-nl-NL.php
  misc/sampleconfigs/autohotspot/NetworkManager/autohotspot.service
  misc/sampleconfigs/autohotspot/dhcpcd/autohotspot-daemon.service
  misc/sampleconfigs/autohotspot/dhcpcd/autohotspot.service
  misc/sampleconfigs/mopidy.conf.sample
  misc/sampleconfigs/mopidy.sample
  misc/sampleconfigs/sudoers-default.sample
  packages-spotify.txt
  requirements-spotify.txt
  requirements.txt
  scripts/helperscripts/Analytics_AfterInstallScript.sh
  scripts/helperscripts/DeleteAllConfig.sh
  scripts/installscripts/install-jukebox.sh
  scripts/installscripts/tests/run_installation_spotify.sh
  scripts/installscripts/tests/test_installation.sh
  scripts/startup-scripts.sh
Labels: enhancement, spotify edition, installation, legacy_v2

#2339 fix: Fix broken utils.get_config_action invocations
  src/jukebox/components/playermpd/__init__.py
Labels: bug, future3

#2345 hotfix pyzmq installation on bullseye (pin version <26)
  installation/routines/setup_jukebox_core.sh
  src/jukebox/jukebox/version.py
Labels: bug, ext dependency, python, future3

#2351 fix: docker build after pyzmq update
  docker/Dockerfile.jukebox
Labels: bug, future3

#2352 feat: Allow to enable/disable Cover Art in Web App & load from filesystem
  documentation/builders/README.md
  documentation/builders/webapp/cover-art.md
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/misc.py
  src/jukebox/components/playermpd/coverart_cache_manager.py
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/App.js
  src/webapp/src/commands/index.js
  src/webapp/src/components/Library/lists/albums/album-list/album-list-item.js
  src/webapp/src/components/Player/index.js
  src/webapp/src/components/Settings/general/index.js
  src/webapp/src/components/Settings/general/show-covers.js
  src/webapp/src/components/Settings/index.js
  src/webapp/src/context/appsettings/context.js
  src/webapp/src/context/appsettings/index.js
Labels: enhancement, future3

#2350 Installation fixes and refactoring
  scripts/helperscripts/inc.helper.sh
  scripts/helperscripts/inc.networkHelper.sh
  scripts/helperscripts/setup_autohotspot.sh
  scripts/installscripts/install-jukebox.sh
  scripts/installscripts/tests/run_installation_autohotspot_NetworkManager.sh
  scripts/installscripts/tests/run_installation_autohotspot_dhcpcd.sh
  scripts/installscripts/tests/run_installation_classic.sh
  scripts/installscripts/tests/run_installation_rfid.sh
  scripts/installscripts/tests/run_installation_spotify.sh
  scripts/installscripts/tests/run_installation_staticip_dhcpcd.sh
Labels: enhancement, installation, legacy_v2

#2355 Fix button function call
  README.md
  components/gpio_control/README.md
  components/gpio_control/example_configs/gpio_setting_rotary_vol_prevnext.ini
  components/gpio_control/example_configs/gpio_settings.ini
  components/gpio_control/example_configs/gpio_settings_rotary_and_led.ini
  components/gpio_control/example_configs/gpio_settings_status_led.ini
  components/gpio_control/function_calls.py
  components/gpio_control/gpio_control.py
  components/gpio_control/test/test_gpio_control.py
  misc/sampleconfigs/gpio_settings.ini.sample
Labels: bug, legacy_v2

#2357 Update default handling for yes/no questions
  components/audio/PirateAudioHAT/setup_pirateAudioHAT.sh
  components/controls/buttons_usb_encoder/setup-buttons-usb-encoder.sh
  components/rfid-reader/PN532/setup_pn532.sh
  components/rfid-reader/RC522/setup_rc522.sh
  scripts/RegisterDevice.py.Multi
Labels: bug, enhancement, legacy_v2
