Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2024-12, with the labels that each got.

#2464 fix: correct function name reference in is_debian_version_at_least()
  installation/includes/02_helpers.sh
Labels: future3

#2466 Fix card swipe detection issue after NTP update
  scripts/daemon_rfid_reader.py
Labels: bug, legacy_v2

#2473 fix wrong usage of variable introduced with 2450
  installation/includes/02_helpers.sh
Labels: installation, future3
