Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2024-05, with the labels that each got.

#2363 (maint) Remove setup-python-dependencies
  .github/workflows/codeql-analysis_v3.yml
Labels: future3

#2366 (maint) fix links
  documentation/developers/README.md
Labels: documentation, future3

#2367 Fix button SecondFunc trigger
  components/gpio_control/GPIODevices/simple_button.py
  components/gpio_control/README.md
  components/gpio_control/test/test_SimpleButton.py
Labels: enhancement, legacy_v2

#2369 Add markdownlint config and action for V2
  .github/workflows/markdown.yml
  .markdownlint-cli2.yaml
  README.md
  ci/README.md
  components/controls/buttons-bluetooth-headphone/README.md
  components/gpio_control/README.md
  components/synchronisation/sync-shared/README.md
  scripts/helperscripts/README.md
Labels: documentation, legacy_v2

#2371 (maint) fix formatting
  README.md
  components/controls/buttons-bluetooth-headphone/README.md
Labels: documentation, legacy_v2

#2338 maint: Use flake8 config file
  .flake8
  .github/workflows/pythonpackage.yml
  components/bluetooth-sink-switch/bt-sink-switch.py
  components/controls/buttons-bluetooth-headphone/bt-buttons.py
  components/controls/buttons_usb_encoder/buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/io_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
  components/gpio_control/config_compatibility.py
  components/gpio_control/function_calls.py
  components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
  scripts/Reader.py
  scripts/Reader.py.Multi
  scripts/Reader.py.experimental
  scripts/Reader.py.experimental.Multi
  scripts/Reader.py.kkmoonRFIDreader
  scripts/Reader.py.original
  scripts/Reader.py.pcsc
  scripts/RegisterDevice.py.Multi
  scripts/daemon_rfid_reader.py
  scripts/helperscripts/organizeFiles.py
Labels: legacy_v2

#2372 add details about cards for RC522
  documentation/developers/rfid/mfrc522_spi.md
Labels: documentation, future3

#2374 document working cards for rc522
  components/rfid-reader/RC522/README.md
Labels: documentation, legacy_v2
