Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2024-11, with the labels that each got.

#2448 Delete tests/htdocs/inc/SetWlanIpMailTest.php
  tests/htdocs/inc/SetWlanIpMailTest.php
Labels: legacy_v2

#2449 Fix FROM as casing warning
  ci/Dockerfile.debian
Labels: legacy_v2

#2451 Docker semantic fix
  docker/Dockerfile.jukebox
Labels: future3

#2435 Fix Spotify authentication
  requirements-spotify.txt
  scripts/installscripts/install-jukebox.sh
Labels: spotify edition, legacy_v2

#2425 Future3/lift 64bit restriction
  installation/includes/02_helpers.sh
  installation/install-jukebox.sh
Labels: enhancement, future3

#2450 Use correct raspi-config command for bookworm
  installation/includes/02_helpers.sh
  src/jukebox/components/rfid/hardware/rdm6300_serial/setup.inc.sh
Labels: bug, needs testing, ext dependency, future3

#2368 Release v2.8.0
  .flake8
  .github/workflows/markdown.yml
  .github/workflows/pythonpackage.yml
  .github/workflows/test_docker_debian_codename_sub.yml
  .markdownlint-cli2.yaml
  README.md
  ci/Dockerfile.debian
  ci/README.md
  components/bluetooth-sink-switch/bt-sink-switch.py
  components/controls/buttons-bluetooth-headphone/README.md
  components/controls/buttons-bluetooth-headphone/bt-buttons.py
  components/controls/buttons_usb_encoder/buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/io_buttons_usb_encoder.py
  components/controls/buttons_usb_encoder/map_buttons_usb_encoder.py
  components/gpio_control/GPIODevices/simple_button.py
  components/gpio_control/README.md
  components/gpio_control/config_compatibility.py
  components/gpio_control/function_calls.py
  components/gpio_control/test/test_SimpleButton.py
  components/rfid-reader/RC522/README.md
  components/smart-home-automation/MQTT-protocol/daemon_mqtt_client.py
  components/synchronisation/sync-shared/README.md
  htdocs/inc.setWlanIpMail.php
  requirements-spotify.txt
  scripts/Reader.py
  scripts/Reader.py.Multi
  scripts/Reader.py.experimental
  scripts/Reader.py.experimental.Multi
  scripts/Reader.py.kkmoonRFIDreader
  scripts/Reader.py.original
  scripts/Reader.py.pcsc
  scripts/RegisterDevice.py.Multi
  scripts/daemon_rfid_reader.py
  scripts/helperscripts/README.md
  scripts/helperscripts/organizeFiles.py
  scripts/installscripts/install-jukebox.sh
  settings/version-number
Labels: Release, legacy_v2

#2332 feat: Add Idle Shutdown Timer support
  documentation/developers/docker.md
  documentation/developers/status.md
  resources/default-settings/jukebox.default.yaml
  src/jukebox/components/timers/__init__.py
  src/jukebox/components/timers/idle_shutdown_timer.py
  src/jukebox/components/timers/volume_fadeout_shutdown_timer.py
  src/jukebox/jukebox/daemon.py
  src/jukebox/jukebox/multitimer.py
  src/webapp/public/locales/de/translation.json
  src/webapp/public/locales/en/translation.json
  src/webapp/src/commands/index.js
  src/webapp/src/components/Settings/timers/index.js
  src/webapp/src/components/Settings/timers/set-timer-dialog.js
  src/webapp/src/components/Settings/timers/timer.js
  src/webapp/src/components/general/Countdown.js
Labels: enhancement, future3

#2455 [maint] Ignore LICENSE file in markdown linter
  .markdownlint-cli2.yaml
Labels: enhancement, future3
