Repository MiczFlor/RPi-Jukebox-RFID, pull requests merged in 2025-02, with the labels that each got.

#2484 Fix the url to Autohotspot docs
  src/webapp/src/components/Settings/autohotspot.js
Labels: enhancement, documentation, future3

#2412 feat: add basic mqtt support
  documentation/builders/components/mqtt/mqtt-integration.md
  documentation/developers/docstring/README.md
  documentation/developers/status.md
  requirements.txt
  src/jukebox/components/mqtt/__init__.py
  src/jukebox/components/mqtt/mqtt_command_alias.py
  src/jukebox/components/mqtt/mqtt_const.py
  src/jukebox/components/mqtt/utils.py
Labels: enhancement, future3

#2493 Bluetooth sink led update for rpi-lgpio
  components/bluetooth-sink-switch/bt-sink-switch.py
Labels: bug, legacy_v2

#2470 Replace RPi.GPIO with rpi-lgpio for V3 future3
  .github/workflows/codeql-analysis_v3.yml
  documentation/developers/rfid/mfrc522_spi.md
  installation/includes/02_helpers.sh
  installation/routines/setup_jukebox_core.sh
  packages-core.txt
  requirements-excluded.txt
  requirements.txt
  src/jukebox/components/hostif/linux/__init__.py
  src/jukebox/components/rfid/hardware/rc522_spi/rc522_spi.py
  src/jukebox/components/rfid/hardware/rc522_spi/requirements.txt
Labels: bug, future3

#2498 fix evdev breakingchange
  src/jukebox/components/rfid/hardware/generic_usb/generic_usb.py
Labels: ext dependency, future3
